# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-EnumConstraints
version:      0.02
version_from: lib/DBIx/EnumConstraints.pm
installdirs:  site
requires:
    Class::Accessor:               
    Test::TempDatabase:            0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
